INSERT INTO faculties (id, name, website, email, phone, address, info) VALUES
	(1, 'Faculty of Biology', 'bioweb.lnu.edu.ua', 'biolog@lnu.edu.ua', '274-03-72, 239-41-53', 'Mykhaila Hrushevskoho Street, 4, Lviv, 79005, Ukraine, 79005', 'Faculty of Biology is ...'),
	(2, 'Faculty of Geography', 'geography.lnu.edu.ua', 'geodekanat@gmail.com', '239-41-62, 272-26-44', 'Address: Doroshenka Street, 41, Lviv, 79000, Ukraine', 'Faculty of Geography is ...'),
	(3, 'Faculty of Geology', 'geology.lnu.edu.ua', 'decanat.geology@ukr.net', '261-60-56, 239-41-56', 'Mykhaila Hryshevskoho Street, 4, Lviv, 79005, Ukraine, 79005', 'Faculty of Geology is ...'),
	(4, 'Faculty of Economics', 'econom.lnu.edu.ua', 'edean@lnu.edu.ua', '239-41-68', 'Svobody Avenue, 18, Lviv, 79008, Ukraine, 79008', 'Faculty of Economics is ...'),
	(5, 'Faculty of Electronics and computer technologies', 'electronics.lnu.edu.ua', 'electronics.faculty@lnu.edu.ua', '261-14-91, 239-47-24, 239-41-82', 'Drahomanova Street, 50, Lviv, 79005, Ukraine', 'Faculty of Electronics and computer technologies is ...'),
	(6, 'Faculty of Journalism', 'journ.lnu.edu.ua', 'journft@lnu.edu.ua', '239-47-51', 'Henerala Chuprynky Street, 49, Lviv, 79044, Україна', 'Faculty of Journalism is ...'),
	(7, 'Faculty of Foreign Languages', 'lingua.lnu.edu.ua', 'lingua.faculty@lnu.edu.ua', '239-47-16', 'Universytetska Street 1/415, Lviv, 79000, Ukraine', 'Faculty of Foreign Languages is ...'),
	(8, 'Faculty of History', 'clio.lnu.edu.ua', 'clio@lnu.edu.ua', '261-03-28', 'Universytetska Street, 1, Lviv, 79000, Ukraine', 'Faculty of History is ...'),
	(9, 'Faculty of Culture and Arts', 'kultart.lnu.edu.ua', 'fkultart@lnu.edu.ua', '239-41-97', 'Valova Street,18, Lviv, 79008, Ukraine', 'Faculty of Culture and Arts is ...'),
	(10, 'Faculty of Mechanics and Mathematics', 'www.mmf.lnu.edu.ua', 'dmmf@lnu.edu.ua', '260-00-09, 239-41-74, 239-47-43', 'Universytetska Street, 1, Lviv, 79000, Ukraine', 'Faculty of Mechanics and Mathematics is ...'),
	(11, 'Faculty of International Relations', 'intrel.lnu.edu.ua', 'intrel.faculty@lnu.edu.ua', '255-43-17', 'Sichovykh Striltsiv Street, 19, Lviv, 79000, Ukraine, 79000', 'Faculty of International Relations is ...'),
	(12, 'Faculty of Pedagogical Education', 'pedagogy.lnu.edu.ua', 'pedosv.fakultet@ukr.net', '239-42-30', 'Tuhan-Baranovskoho Street, 7, Lviv, 79000, Ukraine', 'Faculty of Pedagogical Education is ...'),
	(13, 'Faculty of Applied Mathematics and Informatics', 'ami.lnu.edu.ua', 'ami@lnu.edu.ua', '274-01-80, 239-41-86', 'Universytetska Street 1, Lviv, 79000, Ukraine', 'Faculty of Applied Mathematics and Informatics is ...'),
	(14, 'Faculty of Financial Management and Business', 'financial.lnu.edu.ua', 'financial.faculty@lnu.edu.ua', '235-64-50, 235-86-54', 'Kopernyka Street, 3, Lviv, 79000, Ukraine', 'Faculty of Financial Management and Business is ...'),
	(15, 'Faculty of Physics', 'physics.lnu.edu.ua', 'fiz_dekanat@lnu.edu.ua', '272-70-64', 'Kyryla i Mefodiya Street, 8, Lviv, 79005, Ukraine', 'Faculty of Physics is ...'),
	(16, 'Faculty of Philology', 'philology.lnu.edu.ua', 'filologylnu@gmail.com', '255-41-33, 239-41-58, 239-41-88', 'Universytetska Street, 1, room 232, Lviv, 79000, Ukraine', 'Faculty of Philology is ...'),
	(17, 'Faculty of Philosophy', 'filos.lnu.edu.ua', 'dfilos@lnu.edu.ua', '239-45-79', 'Universytetska Street, 1, Lviv, 79001, Ukraine', 'Faculty of Philosophy is ...'),
	(18, 'Faculty of Chemistry', 'chem.lnu.edu.ua', 'chemdek@lnu.edu.ua', '260-03-91, 239-45-10', 'Kyryla I Mefodiya, 6, Lviv, 79005, Ukraine', 'Faculty of Chemistry is ...'),
	(19, 'Faculty of Law', 'law.lnu.edu.ua', 'law.faculty@lnu.edu.ua', '239-41-02', 'вул. Січових Стрільців, 14, м. Львів, 79000', 'Faculty of Law is ...');
SELECT setval('faculties_id_seq', 19);

INSERT INTO departments (id, name, faculty_id, email, phone, info) VALUES
(1, 'Programming', 13, 'programming.dep.ami@lnu.edu.ua', '(032) 239-41-78', 'The Department provides a number of basic reading courses for “Informatics”, “Applied Mathematics” and “System Analysis” areas at the Faculty of Applied Mathematics and Informatics, for “Mathematics” area at the Faculty of Mechanics and Mathematics and the course “Fundamentals of Informatics” for students of the Faculty of International Relations and the Faculty of Law. In addition, professors of the Department conduct classes for the course “Fundamentals of Informatics” for postgraduate students of all majors.'),
(2, 'Information Systems', 13, 'is.dep.ami@lnu.edu.ua', '(032) 239-45-45', 'In its teaching and methodical practice the Department seeks training of highly qualified specialists in the area of development and application of information – analytical systems for decision -making based on modern information technology, computer technology and mathematical and numerical modeling tools.'),
(3, 'Discrete Analysis and Intelligent System', 13, 'kdais@lnu.edu.ua', '(032) 239-42-11', 'Department of Discrete Analysis and Intelligent System is graduating and prepares bachelors in “Informatics” research area and masters and specialists in “Applied Informatics” research area within the field of knowledge “System Sciences and Cybernetics”. Training is provided by reading courses to choose from intelligent systems, methods of knowledge representation, expert systems, selection and decision-making methods, modeling and forecasting of economic and ecological processes.'),
(4, 'Computational Mathematics', 13, 'cm.dep.ami@lnu.edu.ua', '(032) 239-43-91', 'Department of Computational Mathematics was founded in 1960 under the Faculty of Mechanics and Mathematics. The main reason for the formation of the Department was an urgent need of specialists for contemporary economic complex, who should be able to ensure the proper functioning of the first computers (system software) and to make software and application software for them. The undeniable fact is that this type of chair was one of the first in the former USSR and the first in western Ukraine. Founder (on the initiative of the rector of Lviv University Academic Eugene Lazarenko) and the long head of the department was Professor A. Kostovskyy. By the mid 70’s Department issued specialists – “calculators”, focused on computers BESM, ES and others types system maintenance, the development and support of AMS etc.'),
(5, 'Applied Mathematics', 13, 'kpm@lnu.edu.ua', '(032) 239-41-78', 'Department of Applied Mathematics was founded in 1963. From 1963 to 1988 it was headed by Doctor of Technical Sciences Professor N. P. Fleishman. Since 1988 the Head of the Department is Doctor of Science, Professor, Distinguished Professor of Ivan Franko National University of Lviv, Honored Worker of Education of Ukraine Ya. H. Savula. The Department formed a scientific field of problems of mathematical and computer modeling and optimization of physical – mechanical fields in solid environment. This research area is based on the scientific achievements of professors N. P. Fleyshman and Ya. H. Savula and their students. The modern period of Departments functionality under Professor Ya. H. Savula direction studies characterized variation- projection methods, finite and boundary elements and their application to the analysis and optimal management of physical – mechanical fields. Scientific work is being held on the Department in the field of numerical modeling of solutions of applied problems of different nature from heterogeneous mathematical models and using hybrid schemes of finite and boundary elements methods, in the numerical analysis of nonlinear problems of mathematical physics with application to shell theory, the theory of plasticity and to modeling of transport processes plasma. Scientific researches are focused on their use in science, technology and use for modeling in ecology and medicine.'),
(6, 'Theory of Optimal Processes', 13, 'ktop@lnu.edu.ua', '(032) 239-47-91', 'The Department of Theory of Optimal Processes was founded in 1973 within the framework of the Faculty of Mechanics and Mathematics. The Department provides training students in bachelors degree in “system analysis” and masters degree in the specialty “system analysis and management”.'),
(7, 'Mathematical Modeling of Social and Economics Processes', 13, 'kafmmsep@lnu.edu.ua', '(032) 239-43-51', 'This Department provides specialists preparation in “Social Informatics” research area. Departments scientific areas are mathematical modeling of natural, informational and socio – economics processes and systems; modern informational technologies optimization problems; development of new numerical methods for solving certain classes of problems of algebra, mathematical analysis, differential equations and mathematical physics.');
SELECT setval('departments_id_seq', 7);

INSERT INTO scientific_degrees(id, name) VALUES
(1, 'Кандидат фізико-математичних наук'),
(2, 'Доктор фізико-математичних наук');
SELECT setval('scientific_degrees_id_seq', 2);

INSERT INTO users (id, username, password_hash, first_name, middle_name, last_name, email, phone, info) VALUES
(1, 'oleh', '$2a$10$UW.mzCX478ew48EVaLFRTuVi4AT6v3Qo5XgPm./vR.6/7OZs0DLEW', 'Oleh', 'Bohdanovych', 'Zanevych', 'Oleh.Zanevych@gmail.com', '+380671694179', 'Funny guy:)');

INSERT INTO lecturers (id, first_name, middle_name, last_name, email, phone, info, department_id, scientific_degree_id, academic_status) VALUES
(2, 'Yarema', 'Hryhorovych', 'Savula', 'savula@lnu.edu.ua', '(032) 239-41-86', '<p>Date and place of birth: 14.05.1946, Stryj, Lviv Region, Ukraine ;</p><p>Education (degrees, dates, universities)</p><p>Master, 1969, Ivan Franko National University of Lviv;<br> Kandidate of Sciences (physics and mathematics), 11. 07. 1973, Ivan Franko National University of Lviv;<br> Doctor of Sciences (physics and mathematics), 19.07.1987, Kazan University, Russia;<br> 1976 – scientific internship at the Lomonosov State University of Moscow;<br> 1977 – 1978 scientific internship at the Brno University of Technology;<br> 1998 -1999 scientific internship at the Vienna University of Technology;</p><p>Career/Employment (employers, positions and dates)</p><p>Assistant, Ivan Franko National University of Lviv, from 1972 to 1974;<br> Docent, Ivan Franko National University of Lviv, from 1974 to 1988;<br> Professor, Ivan Franko National University of Lviv, from 1988 to1989;<br> Head of Department of Applied Mathematics, Ivan Franko National University of Lviv, from 1989 to 2014;<br> Dean of Faculty of Applied Mathematics and Informatics, Ivan Franko National University of Lviv, from 1996 to 2015;<br> Head of Department of Applied Mathematics, Ivan Franko National University of Lviv, from 2016;</p><p>Fellowships, Membership of Professional Societies</p><p>Member of National Committee of Theoretical and Applied Mechanics;<br> Member of Ukrainian Academy of Science of High School;<br> 1995 – Team Leader of the Eurasia Grant “ Connection of the Lviv University to the Internet”;<br> 2001-2004 Team Leader of the Intas Grant No: 00751;<br> 2005 – NATO scholarship at the Miskolc University, Hungary;<br> 2009-2010 Team Leader of the TEMPUS Grant HES-00232-2008 “Educational Centers Network on Modern Technologies of Local Governing”,<br> 2009, 2010 Lecturer of IX and X International Economic Forum –Lviv Truskavets;<br> 2012, Team member of Grant “Education for Entrepreneurship and Innovation (E4E&amp;I)”, Stockholm University, Sweden.<br> 2012-2014, Team member of Tempus grant EARL: Eastern-European Qualification Framework in the Field of Informatics and Management.</p>', 5, 2, 'PROFESSOR');
SELECT setval('users_id_seq', 2);